#docker-compose.yml

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: fabtrack_sql_server
    environment:
      SA_PASSWORD: "Admin!@#123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_server_data:/var/opt/mssql

volumes:
  sql_server_data: