name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with: 
        compose-file: "./docker-compose.yml"

    - name: Wait for MSSQL to be ready
      run: |
        until docker-compose exec -T db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Admin!@#123' -Q 'SELECT 1'; do
          echo "Waiting for SQL Server to be up..."
          sleep 5
        done

    - name: Create Database
      run: |
        docker-compose exec -T db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Admin!@#123' -Q 'CREATE DATABASE FabTrackDB;'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
